print("welocme to my world ( quize about counrties around the world")
satrt_code = input  ("press Enter to sart")
print ("let 's begin")
input (" Question 1")
input (" Question 1 : what is the chapital city of Sri lanka")
input ("The answers are A Sri jayawardenepura kotte b Colombo C welitong ")
print ("This is  your answer."+answer  "" )
print (" if the answer is B ")
print ("Well done you got is right ")
print (" if the answer is C  ")
print (" Uh oh! That's not right you got it worng ")
input (" Question 2 ")
input (" Question 2 : what is the colours of the flag in Sri Lanka ")
input (" The answers are A Red and Yellow B Blue C Green")
print (" if the answers is A")
print(" well done That is right ")
print(" if the answer is b and C ")
print(" Uh oh! you got it worng ")
input(" Question 3")
input(" Question 3: what are the foods in Sri Lanka ")
input(" The answers are A rice B ")